import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex absolute bg-[#dbdbdb] w-full h-full items-center justify-center">
        <div className="flex flex-col gap-8 p-8 rounded-xl bg-white">
          <h1 className="text-center">Biodata</h1>
          <div className="flex justify-between items-center">
            <h2>Ahmad Gani</h2>
            <a href="mailto:ahmadxgani01@gmail.com" className="bg-[#03a9f4] p-2 text-white no-underline rounded-lg">
              Contact Me!
            </a>
          </div>
          <div className="flex justify-between gap-2">
            <div>
              <h3 className="text-center">Hobi</h3>
              <ul>
                <li>Ngoding</li>
                <li>Berenang</li>
                <li>Tidur</li>
              </ul>
            </div>
            <div>
              <h3 className="text-center">Pendidikan</h3>
              <ol>
                <li>SD Parungseah 2</li>
                <li>SMPN 1 Kota Sukabumi</li>
                <li>SMK IT Al-fath</li>
              </ol>
            </div>
          </div>
          <div className="flex flex-col gap-4">
            <h3 className="text-center">Social Media</h3>
            <div className="flex justify-center gap-4">
              <a href="https://github.com/query-gani">
                <Image width={47} height={47} src="/icon/github.png" alt="github" />
              </a>
              <a href="https://linkedin.com/in/ahmad-gani">
                <Image width={47} height={47} src="/icon/linkedin.png" alt="linkedin" />
              </a>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
