import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.center}>
        <div className={`${styles.card} ${styles.flex}`}>
          <h1 className={styles["text-center"]}>Biodata</h1>
          <div className={`${styles.flex} ${styles.between} ${styles.name}`}>
            <h2>Ahmad Gani</h2>
            <a href="mailto:ahmadxgani01@gmail.com" className={`${styles.button}`}>
              Contact Me!
            </a>
          </div>
          <div className={`${styles.flex} ${styles.between} ${styles.lists}`}>
            <div>
              <h3 className={styles["text-center"]}>Hobi</h3>
              <ul>
                <li>Ngoding</li>
                <li>Berenang</li>
                <li>Tidur</li>
              </ul>
            </div>
            <div>
              <h3 className={styles["text-center"]}>Pendidikan</h3>
              <ol>
                <li>SD Parungseah 2</li>
                <li>SMPN 1 Kota Sukabumi</li>
                <li>SMK IT Al-fath</li>
              </ol>
            </div>
          </div>
          <div className={`${styles.flex} ${styles.sosmed}`}>
            <h3 className={styles["text-center"]}>Social Media</h3>
            <div className={`${styles.flex} ${styles.links}`}>
              <a href="https://github.com/query-gani">
                <Image width={47} height={47} src="/icon/github.png" alt="github" />
              </a>
              <a href="https://linkedin.com/in/ahmad-gani">
                <Image width={47} height={47} src="/icon/linkedin.png" alt="linkedin" />
              </a>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
